name: Tagged Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: persistent-code-lore-linux-x86_64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: persistent-code-lore-windows-x86_64
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: persistent-code-lore-macos-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: persistent-code-lore-macos-aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          strip target/${{ matrix.target }}/release/chat-history-consolidator

      - name: Strip binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          strip target/${{ matrix.target }}/release/chat-history-consolidator.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            target/${{ matrix.target }}/release/chat-history-consolidator*
          retention-days: 30

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find ./artifacts -name "chat-history-consolidator*" -exec cp {} ./release-assets/ \;
          
          # Create checksums
          cd release-assets
          for file in *; do
            if [[ "$file" == *.exe ]]; then
              sha256sum "$file" > "${file}.sha256"
            else
              sha256sum "$file" > "${file}.sha256"
            fi
          done
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push-to-repo:
    name: Push to persistent-code-lore
    runs-on: ubuntu-latest
    needs: [build, release]
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add target repository as remote
        run: |
          git remote add target https://github.com/davz33/persistent-code-lore.git

      - name: Push to target repository
        run: |
          # Push all branches and tags
          git push target --all
          git push target --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts for target repo
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create release in target repository
        run: |
          # Install gh CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

          # Prepare release assets
          mkdir -p release-assets
          find ./artifacts -name "chat-history-consolidator*" -exec cp {} ./release-assets/ \;
          
          # Create checksums
          cd release-assets
          for file in *; do
            sha256sum "$file" > "${file}.sha256"
          done
          cd ..

          # Create release in target repository
          gh release create ${{ github.ref_name }} \
            --repo davz33/persistent-code-lore \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release from chat-history-consolidator" \
            ./release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
